=begin
#Ahello REST API documentation

#На данной странице вы можете выполнять запросы к API, для этого необходимо указать 'appId', который  был передан вам сотрудниками тех. поддержки в поле api_key. Укажите также PartnerUserId (это CRM Id пользователя или его email ), partnerUserId передается в заголовке запроса. Важно!!! ApiKeys-аутентификация c указанием только ключа appId в ближайшее время будет работать только для данной страницы документации. Для реальных сценариев интеграции необходимо использовать HMAC-аутентификацию. В ближайшее время появится раздел помощи по основным вопросам работы с API

OpenAPI spec version: v1
Contact: petrunin@action-media.ru
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'

# Unit tests for AktionClient::ErmBusApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ErmBusApi' do
  before do
    # run before each test
    @instance = AktionClient::ErmBusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ErmBusApi' do
    it 'should create an instance of ErmBusApi' do
      expect(@instance).to be_instance_of(AktionClient::ErmBusApi)
    end
  end

  # unit tests for erm_bus_get_dictionaty
  # @param domain_name 
  # @param dictionary_name 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'erm_bus_get_dictionaty test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for erm_bus_get_first_question
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'erm_bus_get_first_question test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for erm_bus_get_preview
  # Возвращает вопрос с ответами и содержанием скрипта
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'erm_bus_get_preview test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for erm_bus_get_question
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'erm_bus_get_question test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for erm_bus_get_script_list
  # Возвращает список скриптов по головному продукту
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'erm_bus_get_script_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for erm_bus_get_token
  # @param domain_name 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'erm_bus_get_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for erm_bus_interaction
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'erm_bus_interaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for erm_bus_save_answer
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'erm_bus_save_answer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
