=begin
#Ahello REST API documentation

#На данной странице вы можете выполнять запросы к API, для этого необходимо указать 'appId', который  был передан вам сотрудниками тех. поддержки в поле api_key. Укажите также PartnerUserId (это CRM Id пользователя или его email ), partnerUserId передается в заголовке запроса. Важно!!! ApiKeys-аутентификация c указанием только ключа appId в ближайшее время будет работать только для данной страницы документации. Для реальных сценариев интеграции необходимо использовать HMAC-аутентификацию. В ближайшее время появится раздел помощи по основным вопросам работы с API

OpenAPI spec version: v1
Contact: petrunin@action-media.ru
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'

# Unit tests for AktionClient::PhoneCallsApiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PhoneCallsApiApi' do
  before do
    # run before each test
    @instance = AktionClient::PhoneCallsApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhoneCallsApiApi' do
    it 'should create an instance of PhoneCallsApiApi' do
      expect(@instance).to be_instance_of(AktionClient::PhoneCallsApiApi)
    end
  end

  # unit tests for phone_calls_api_call_mango
  # @param target 
  # @param user 
  # @param serverurl 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'phone_calls_api_call_mango test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_change_phone_call_owner
  # Смена ответственного на звонке
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'phone_calls_api_change_phone_call_owner test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_complete_phone_call
  # Завершить звонок
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'phone_calls_api_complete_phone_call test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_create_phone_call_request_new
  # Назначение свободных клиентов менеджерам
  # Internal api method
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'phone_calls_api_create_phone_call_request_new test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_demo_access_log
  # @param customer_id 
  # @param system_user_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<DemoAccessLogResult>]
  describe 'phone_calls_api_demo_access_log test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_end_phone_call
  # @param pc 
  # @param [Hash] opts the optional parameters
  # @return [Result]
  describe 'phone_calls_api_end_phone_call test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_export_free_customers
  # Получает xlsx файл экспорта свободных клиентов.  Кол-во экспортированных клиентов фиксируется для проверки лимитов на экспорт.
  # @param customer_ids 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'phone_calls_api_export_free_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_about_block
  # @param pin 
  # @param campaignid 
  # @param filter_nr 
  # @param main_product_id 
  # @param [Hash] opts the optional parameters
  # @return [MainProductInformation]
  describe 'phone_calls_api_get_about_block test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_action_statuses_by_campaign_id
  # Получить результаты действий для кампании обзвона.
  # @param campaign_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<ActionStatus>]
  describe 'phone_calls_api_get_action_statuses_by_campaign_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_activity
  # @param customer_id 
  # @param campaignid 
  # @param system_user_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<ActivityLogItemCore>]
  describe 'phone_calls_api_get_activity test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_activity_logs
  # @param customer_id 
  # @param customer_type 
  # @param campaignid 
  # @param [Hash] opts the optional parameters
  # @return [Array<ActivityLogItem>]
  describe 'phone_calls_api_get_activity_logs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_all_okp
  # @param [Hash] opts the optional parameters
  # @return [Array<PhoneCall>]
  describe 'phone_calls_api_get_all_okp test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_campaign_by_id
  # Получить кампанию обзвона по Id.
  # @param campaign_id 
  # @param [Hash] opts the optional parameters
  # @return [Campaign]
  describe 'phone_calls_api_get_campaign_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_campaigns
  # Получить кампании обзвона по подразделению текущего пользователя.
  # @param [Hash] opts the optional parameters
  # @return [Array<Campaign>]
  describe 'phone_calls_api_get_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_campaigns_by_partners
  # Получить кампании обзвона по всей филиальной сети партнера
  # @param [Hash] opts the optional parameters
  # @return [Array<Campaign>]
  describe 'phone_calls_api_get_campaigns_by_partners test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_contact_block
  # @param customer_id 
  # @param customer_type 
  # @param parent_account_name 
  # @param job_title 
  # @param [Hash] opts the optional parameters
  # @return [Array<OutBoxPhoneCall>]
  describe 'phone_calls_api_get_contact_block test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_free_customers_search_filters
  # @param [Hash] opts the optional parameters
  # @return [FreeCustomersSearchFilters]
  describe 'phone_calls_api_get_free_customers_search_filters test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_itm_campaigns
  # @param [Hash] opts the optional parameters
  # @return [Array<ItmCampaigns>]
  describe 'phone_calls_api_get_itm_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_my_phone_calls
  # @param date 
  # @param sort_on 
  # @param sort_order 
  # @param page_num 
  # @param page_len 
  # @param search_text 
  # @param [Hash] opts the optional parameters
  # @return [PhoneCallPartial]
  describe 'phone_calls_api_get_my_phone_calls test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_my_phone_calls_by_date
  # @param date 
  # @param date_end 
  # @param sort_on 
  # @param sort_order 
  # @param page_num 
  # @param page_len 
  # @param search_text 
  # @param [Hash] opts the optional parameters
  # @return [PhoneCallPartial]
  describe 'phone_calls_api_get_my_phone_calls_by_date test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_not_dialed_calls_count
  # @param campaign_id 
  # @param activity_id 
  # @param [Hash] opts the optional parameters
  # @return [BOOLEAN]
  describe 'phone_calls_api_get_not_dialed_calls_count test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_okp_campaigns
  # @param [Hash] opts the optional parameters
  # @return [Array<OkpCampaign>]
  describe 'phone_calls_api_get_okp_campaigns test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_operator_stat
  # @param [Hash] opts the optional parameters
  # @return [OperatorStat]
  describe 'phone_calls_api_get_operator_stat test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_out_box
  # @param date 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :order 
  # @option opts [String] :desc 
  # @option opts [String] :category 
  # @return [OutBox]
  describe 'phone_calls_api_get_out_box test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_call_by_id
  # Получить звонок  по Id
  # @param call_id 
  # @param [Hash] opts the optional parameters
  # @return [PhoneCall]
  describe 'phone_calls_api_get_phone_call_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_call_queue_by_pin
  # Карточка звонка. Есть activityId null - берется из очереди  если activityId !null - берется звонок по id
  # @param campaign_id 
  # @param pin 
  # @param account_id 
  # @param activity_id id звонка
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :is_multi_campaign мультикампании
  # @return [OutBox]
  describe 'phone_calls_api_get_phone_call_queue_by_pin test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_calls_by_campaign_id
  # Получить звонки  по кампании.
  # @param campaign_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<PhoneCall>]
  describe 'phone_calls_api_get_phone_calls_by_campaign_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_calls_by_campaign_id_today
  # Получить звонки  по кампании.
  # @param campaign_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<PhoneCall>]
  describe 'phone_calls_api_get_phone_calls_by_campaign_id_today test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_calls_by_campaing
  # @param campaign_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<PhoneCall>]
  describe 'phone_calls_api_get_phone_calls_by_campaing test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_calls_by_customer
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<PhoneCall>]
  describe 'phone_calls_api_get_phone_calls_by_customer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_calls_by_primary
  # @param primary_phone_call_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<PhoneCall>]
  describe 'phone_calls_api_get_phone_calls_by_primary test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_calls_by_top_partner
  # Получить звонки  по головному партнеру.
  # @param date 
  # @param [Hash] opts the optional parameters
  # @return [Array<PhoneCall>]
  describe 'phone_calls_api_get_phone_calls_by_top_partner test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_phone_calls_by_user_id
  # Получить список звонков  по пользователю
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [Array<PhoneCall>]
  describe 'phone_calls_api_get_phone_calls_by_user_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_previews
  # @param main_product_id 
  # @param [Hash] opts the optional parameters
  # @return [MainProductInformation]
  describe 'phone_calls_api_get_previews test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_redial_count_by_activity_id
  # @param activity_id 
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'phone_calls_api_get_redial_count_by_activity_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_get_script_type
  # @param company_id 
  # @param [Hash] opts the optional parameters
  # @return [ScriptType]
  describe 'phone_calls_api_get_script_type test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_help_call_async
  # @param from 
  # @param to 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'phone_calls_api_help_call_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_import_mp3_files
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'phone_calls_api_import_mp3_files test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_import_mp3_filesabase64
  # @param base64 
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'phone_calls_api_import_mp3_filesabase64 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_import_phone_calls
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'phone_calls_api_import_phone_calls test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_search_free_customers
  # Поиск свободных клиентов
  # Internal api method
  # @param search 
  # @param [Hash] opts the optional parameters
  # @return [Array<Customer>]
  describe 'phone_calls_api_search_free_customers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_search_free_customers_paged
  # Поиск свободных клиентов  Метод, предназначенный для вызова напрямую из клиента
  # Internal api method
  # @param customer_type_id 
  # @param job_type_ids_str 
  # @param industry_ids_str 
  # @param region_ids_str 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :sale_forecast_id 
  # @option opts [String] :accounting_type_id 
  # @option opts [String] :revenue_id 
  # @option opts [String] :name_filter 
  # @option opts [BOOLEAN] :only_with_phone 
  # @option opts [BOOLEAN] :without_calls 
  # @option opts [String] :sort_on 
  # @option opts [String] :sort_order 
  # @option opts [Integer] :page_num 
  # @option opts [Integer] :page_len 
  # @option opts [String] :search_text 
  # @return [CustomerSimplePaged]
  describe 'phone_calls_api_search_free_customers_paged test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_set_phone_call_owner
  # Установить ответственного на звонке
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'phone_calls_api_set_phone_call_owner test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_spy_call_async
  # @param from 
  # @param to 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'phone_calls_api_spy_call_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for phone_calls_api_war_call_async
  # @param from 
  # @param to 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'phone_calls_api_war_call_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
