=begin
#Ahello REST API documentation

#На данной странице вы можете выполнять запросы к API, для этого необходимо указать 'appId', который  был передан вам сотрудниками тех. поддержки в поле api_key. Укажите также PartnerUserId (это CRM Id пользователя или его email ), partnerUserId передается в заголовке запроса. Важно!!! ApiKeys-аутентификация c указанием только ключа appId в ближайшее время будет работать только для данной страницы документации. Для реальных сценариев интеграции необходимо использовать HMAC-аутентификацию. В ближайшее время появится раздел помощи по основным вопросам работы с API

OpenAPI spec version: v1
Contact: petrunin@action-media.ru
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'

# Unit tests for AktionClient::SalesApiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SalesApiApi' do
  before do
    # run before each test
    @instance = AktionClient::SalesApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SalesApiApi' do
    it 'should create an instance of SalesApiApi' do
      expect(@instance).to be_instance_of(AktionClient::SalesApiApi)
    end
  end

  # unit tests for sales_api_approve_sales_agreement
  # @param request_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'sales_api_approve_sales_agreement test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_api_get_invoice_file
  # Получает файл счета-фактуру по id
  # @param invoice_id 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'sales_api_get_invoice_file test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_api_get_prev_period
  # получаем последнюю дату работы
  # @param date 
  # @param [Hash] opts the optional parameters
  # @return [PrevPeriod]
  describe 'sales_api_get_prev_period test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_api_get_prev_period_bool
  # @param [Hash] opts the optional parameters
  # @return [BOOLEAN]
  describe 'sales_api_get_prev_period_bool test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sales_api_reject_sales_agreement
  # @param request_id 
  # @param comment 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'sales_api_reject_sales_agreement test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
