=begin
#Ahello REST API documentation

#На данной странице вы можете выполнять запросы к API, для этого необходимо указать 'appId', который  был передан вам сотрудниками тех. поддержки в поле api_key. Укажите также PartnerUserId (это CRM Id пользователя или его email ), partnerUserId передается в заголовке запроса. Важно!!! ApiKeys-аутентификация c указанием только ключа appId в ближайшее время будет работать только для данной страницы документации. Для реальных сценариев интеграции необходимо использовать HMAC-аутентификацию. В ближайшее время появится раздел помощи по основным вопросам работы с API

OpenAPI spec version: v1
Contact: petrunin@action-media.ru
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'

# Unit tests for AktionClient::SupportApiApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SupportApiApi' do
  before do
    # run before each test
    @instance = AktionClient::SupportApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SupportApiApi' do
    it 'should create an instance of SupportApiApi' do
      expect(@instance).to be_instance_of(AktionClient::SupportApiApi)
    end
  end

  # unit tests for support_api_approve_confirmation_request
  # @param request_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'support_api_approve_confirmation_request test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_change_support_manager
  # Изменяет менеджера сопровождения
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'support_api_change_support_manager test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_get_company_owners
  # Получает список операторов, отвечающих за кампанию прозвона
  # @param campaign_id 
  # @param [Hash] opts the optional parameters
  # @return [GetPhoneCallOwnersByCampaignIdResult]
  describe 'support_api_get_company_owners test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_get_confirmation_requests_completed
  # @param date 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'support_api_get_confirmation_requests_completed test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_get_confirmation_requests_in_progress
  # @param date 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'support_api_get_confirmation_requests_in_progress test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_get_invoices_reports
  # Получает список отчетов по счетам-фактурам
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partner_id 
  # @return [Array<GetInvoicesResult>]
  describe 'support_api_get_invoices_reports test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_get_managers_model
  # Получает список управляемых манеджеров.   Поддерживает поиск и пагинацию
  # @param page_num 
  # @param page_len 
  # @param sort_on 
  # @param sort_order 
  # @param search_text 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partner_ids 
  # @return [ManagerListPaged]
  describe 'support_api_get_managers_model test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_get_order_reports
  # Получает список отчетов по счетам
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partner_id 
  # @return [Array<GetOrdersResult>]
  describe 'support_api_get_order_reports test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_get_supported_licenses
  # Получает лицензии сопровождаемые партнером.   Лицензия содержит информацию о действии сопровождения
  # @param [Hash] opts the optional parameters
  # @option opts [String] :partner_id 
  # @return [Array<SupportedLicense>]
  describe 'support_api_get_supported_licenses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_get_supported_licenses2
  # Получает лицензии сопровождаемые партнером.   Поддерживает поиск и пагинацию  Лицензия содержит информацию о действии сопровождения
  # @param partner_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :support_system_user_id 
  # @option opts [Integer] :page_num 
  # @option opts [Integer] :page_len 
  # @option opts [String] :sort_on 
  # @option opts [String] :sort_order 
  # @option opts [String] :search_text 
  # @return [SupportedLicensesPaged]
  describe 'support_api_get_supported_licenses2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_process_support_action
  # Отрабатывает действие сопровождения.
  # @param model 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'support_api_process_support_action test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for support_api_reject_confirmation_request
  # @param request_id 
  # @param comment 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'support_api_reject_confirmation_request test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
