=begin
#Ahello REST API documentation

#На данной странице вы можете выполнять запросы к API, для этого необходимо указать 'appId', который  был передан вам сотрудниками тех. поддержки в поле api_key. Укажите также PartnerUserId (это CRM Id пользователя или его email ), partnerUserId передается в заголовке запроса. Важно!!! ApiKeys-аутентификация c указанием только ключа appId в ближайшее время будет работать только для данной страницы документации. Для реальных сценариев интеграции необходимо использовать HMAC-аутентификацию. В ближайшее время появится раздел помощи по основным вопросам работы с API

OpenAPI spec version: v1
Contact: petrunin@action-media.ru
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'date'

module AktionClient
  class ActivityLogItem
    attr_accessor :activity_id

    attr_accessor :call_reason

    attr_accessor :decline_reason

    attr_accessor :call_result

    attr_accessor :is_phone_call

    attr_accessor :contact

    attr_accessor :party_id

    attr_accessor :owner

    attr_accessor :actual_end

    attr_accessor :phone_call_description

    attr_accessor :regarding_object_id

    attr_accessor :next_call_date

    attr_accessor :campaign_name

    attr_accessor :cust_name

    attr_accessor :product_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'activity_id' => :'activityId',
        :'call_reason' => :'callReason',
        :'decline_reason' => :'declineReason',
        :'call_result' => :'callResult',
        :'is_phone_call' => :'isPhoneCall',
        :'contact' => :'contact',
        :'party_id' => :'partyId',
        :'owner' => :'owner',
        :'actual_end' => :'actualEnd',
        :'phone_call_description' => :'phoneCallDescription',
        :'regarding_object_id' => :'regardingObjectId',
        :'next_call_date' => :'nextCallDate',
        :'campaign_name' => :'campaignName',
        :'cust_name' => :'custName',
        :'product_name' => :'productName'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'activity_id' => :'String',
        :'call_reason' => :'String',
        :'decline_reason' => :'String',
        :'call_result' => :'String',
        :'is_phone_call' => :'BOOLEAN',
        :'contact' => :'EntityReference',
        :'party_id' => :'EntityReference',
        :'owner' => :'EntityReference',
        :'actual_end' => :'DateTime',
        :'phone_call_description' => :'String',
        :'regarding_object_id' => :'EntityReference',
        :'next_call_date' => :'DateTime',
        :'campaign_name' => :'String',
        :'cust_name' => :'String',
        :'product_name' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'activityId')
        self.activity_id = attributes[:'activityId']
      end

      if attributes.has_key?(:'callReason')
        self.call_reason = attributes[:'callReason']
      end

      if attributes.has_key?(:'declineReason')
        self.decline_reason = attributes[:'declineReason']
      end

      if attributes.has_key?(:'callResult')
        self.call_result = attributes[:'callResult']
      end

      if attributes.has_key?(:'isPhoneCall')
        self.is_phone_call = attributes[:'isPhoneCall']
      end

      if attributes.has_key?(:'contact')
        self.contact = attributes[:'contact']
      end

      if attributes.has_key?(:'partyId')
        self.party_id = attributes[:'partyId']
      end

      if attributes.has_key?(:'owner')
        self.owner = attributes[:'owner']
      end

      if attributes.has_key?(:'actualEnd')
        self.actual_end = attributes[:'actualEnd']
      end

      if attributes.has_key?(:'phoneCallDescription')
        self.phone_call_description = attributes[:'phoneCallDescription']
      end

      if attributes.has_key?(:'regardingObjectId')
        self.regarding_object_id = attributes[:'regardingObjectId']
      end

      if attributes.has_key?(:'nextCallDate')
        self.next_call_date = attributes[:'nextCallDate']
      end

      if attributes.has_key?(:'campaignName')
        self.campaign_name = attributes[:'campaignName']
      end

      if attributes.has_key?(:'custName')
        self.cust_name = attributes[:'custName']
      end

      if attributes.has_key?(:'productName')
        self.product_name = attributes[:'productName']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          activity_id == o.activity_id &&
          call_reason == o.call_reason &&
          decline_reason == o.decline_reason &&
          call_result == o.call_result &&
          is_phone_call == o.is_phone_call &&
          contact == o.contact &&
          party_id == o.party_id &&
          owner == o.owner &&
          actual_end == o.actual_end &&
          phone_call_description == o.phone_call_description &&
          regarding_object_id == o.regarding_object_id &&
          next_call_date == o.next_call_date &&
          campaign_name == o.campaign_name &&
          cust_name == o.cust_name &&
          product_name == o.product_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [activity_id, call_reason, decline_reason, call_result, is_phone_call, contact, party_id, owner, actual_end, phone_call_description, regarding_object_id, next_call_date, campaign_name, cust_name, product_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AktionClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
