=begin
#Ahello REST API documentation

#На данной странице вы можете выполнять запросы к API, для этого необходимо указать 'appId', который  был передан вам сотрудниками тех. поддержки в поле api_key. Укажите также PartnerUserId (это CRM Id пользователя или его email ), partnerUserId передается в заголовке запроса. Важно!!! ApiKeys-аутентификация c указанием только ключа appId в ближайшее время будет работать только для данной страницы документации. Для реальных сценариев интеграции необходимо использовать HMAC-аутентификацию. В ближайшее время появится раздел помощи по основным вопросам работы с API

OpenAPI spec version: v1
Contact: petrunin@action-media.ru
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'date'

module AktionClient
  class GetSeminarByPublisherGroup
    attr_accessor :id

    attr_accessor :system_user_name

    attr_accessor :created_on

    attr_accessor :name

    attr_accessor :city_name

    attr_accessor :campaign_name

    attr_accessor :date

    attr_accessor :publisher_group_name

    attr_accessor :publisher_group_id

    attr_accessor :new_mainproductid

    attr_accessor :pres

    attr_accessor :seminar_type_name

    attr_accessor :url

    attr_accessor :description

    attr_accessor :campaign_id

    attr_accessor :partner_name

    attr_accessor :partner_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'system_user_name' => :'systemUserName',
        :'created_on' => :'createdOn',
        :'name' => :'name',
        :'city_name' => :'cityName',
        :'campaign_name' => :'campaignName',
        :'date' => :'date',
        :'publisher_group_name' => :'publisherGroupName',
        :'publisher_group_id' => :'publisherGroupId',
        :'new_mainproductid' => :'new_mainproductid',
        :'pres' => :'pres',
        :'seminar_type_name' => :'seminarTypeName',
        :'url' => :'url',
        :'description' => :'description',
        :'campaign_id' => :'campaignId',
        :'partner_name' => :'partnerName',
        :'partner_id' => :'partnerId'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'system_user_name' => :'String',
        :'created_on' => :'DateTime',
        :'name' => :'String',
        :'city_name' => :'String',
        :'campaign_name' => :'String',
        :'date' => :'DateTime',
        :'publisher_group_name' => :'String',
        :'publisher_group_id' => :'Integer',
        :'new_mainproductid' => :'String',
        :'pres' => :'String',
        :'seminar_type_name' => :'String',
        :'url' => :'String',
        :'description' => :'String',
        :'campaign_id' => :'String',
        :'partner_name' => :'String',
        :'partner_id' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'systemUserName')
        self.system_user_name = attributes[:'systemUserName']
      end

      if attributes.has_key?(:'createdOn')
        self.created_on = attributes[:'createdOn']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'cityName')
        self.city_name = attributes[:'cityName']
      end

      if attributes.has_key?(:'campaignName')
        self.campaign_name = attributes[:'campaignName']
      end

      if attributes.has_key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.has_key?(:'publisherGroupName')
        self.publisher_group_name = attributes[:'publisherGroupName']
      end

      if attributes.has_key?(:'publisherGroupId')
        self.publisher_group_id = attributes[:'publisherGroupId']
      end

      if attributes.has_key?(:'new_mainproductid')
        self.new_mainproductid = attributes[:'new_mainproductid']
      end

      if attributes.has_key?(:'pres')
        self.pres = attributes[:'pres']
      end

      if attributes.has_key?(:'seminarTypeName')
        self.seminar_type_name = attributes[:'seminarTypeName']
      end

      if attributes.has_key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.has_key?(:'campaignId')
        self.campaign_id = attributes[:'campaignId']
      end

      if attributes.has_key?(:'partnerName')
        self.partner_name = attributes[:'partnerName']
      end

      if attributes.has_key?(:'partnerId')
        self.partner_id = attributes[:'partnerId']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          system_user_name == o.system_user_name &&
          created_on == o.created_on &&
          name == o.name &&
          city_name == o.city_name &&
          campaign_name == o.campaign_name &&
          date == o.date &&
          publisher_group_name == o.publisher_group_name &&
          publisher_group_id == o.publisher_group_id &&
          new_mainproductid == o.new_mainproductid &&
          pres == o.pres &&
          seminar_type_name == o.seminar_type_name &&
          url == o.url &&
          description == o.description &&
          campaign_id == o.campaign_id &&
          partner_name == o.partner_name &&
          partner_id == o.partner_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, system_user_name, created_on, name, city_name, campaign_name, date, publisher_group_name, publisher_group_id, new_mainproductid, pres, seminar_type_name, url, description, campaign_id, partner_name, partner_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AktionClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
